FROM node:16-alpine as build-deps
# WORKDIR /dev-ui
RUN ls
COPY dev-ui/package.json ./
RUN npm install
COPY dev-ui ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-deps /build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]