FROM python:3.10-slim-buster

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get -y dist-upgrade

RUN apt-get -y install \
	apt-utils \
    build-essential \
    gcc \
	ffmpeg \
	libsm6 \
	libxext6

COPY analyzer/requirements.txt phoenix/analyzer/requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r phoenix/analyzer/requirements.txt
