FROM node:16-alpine as build-deps
ARG PHX_API_URL
COPY ui-webapp/package.json ./
RUN npm install
COPY ui-webapp ./
RUN REACT_APP_API_URL=${PHX_API_URL} npm run build

FROM nginx:stable-alpine
COPY --from=build-deps /build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]