FROM mongo

COPY ./db/startup.sh /scripts/startup.sh
COPY ./db/initialize-rs.sh /scripts/initialize-rs.sh
COPY ./db/mongod.conf /etc/mongod.conf
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/e1f115e4ca285c3c24e847c4dd4be955e0ed51c2/wait-for-it.sh /scripts/wait-for-it.sh
RUN chmod +x /scripts/wait-for-it.sh
run ls /
run ls .

CMD ["./scripts/startup.sh"]
